server:
    port: 8080
    name: auth-center-dev
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/rainsunset_auth?allowMultiQueries=true
        username: root
        password: root
    redis:
        enabled: true
        database: 0
        timeout: 10000
        cluster:
            nodes:
            - 192.168.99.104:7000
            - 192.168.99.104:7001
            - 192.168.99.104:7002
            max-redirects: 3
        jedis:
            pool:
                min-idle: 8
                max-idle: 500
                max-active: 2000
                max-wait: 10000
info:
    service-info: auth-center-dev
    api-doc: /swagger-ui.html
swagger:
    basePath: com.ligw
    title: AuthCenter-API
    description: API信息有疑问请联系相关开发人员
    contact: ligw
    version: @project.version@

# 定时任务多线程执行配置
# 核心线程数
async-executor-thread:
    core-pool-size: 3
    max-pool-size: 7
    queue-capacity: 2
    name-prefix: async_service_
